name: Release Please

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: Setup Go
        uses: actions/setup-go@v5
        if: ${{ steps.release.outputs.releases_created }}
        with:
          go-version: '1.24'

      - name: Test shared package
        if: ${{ steps.release.outputs['shared--release_created'] }}
        run: |
          cd shared
          go test ./...

      - name: Build and test app1
        if: ${{ steps.release.outputs['app1--release_created'] }}
        run: |
          cd app1
          go mod tidy
          go build .
          go test ./...

      - name: Build and test app2  
        if: ${{ steps.release.outputs['app2--release_created'] }}
        run: |
          cd app2
          go mod tidy
          go build .
          go test ./...

      - name: Tag shared release
        if: ${{ steps.release.outputs['shared--release_created'] }}
        run: |
          git tag "shared/v${{ steps.release.outputs['shared--version'] }}"
          git push origin "shared/v${{ steps.release.outputs['shared--version'] }}"

      - name: Tag app1 release
        if: ${{ steps.release.outputs['app1--release_created'] }}
        run: |
          git tag "app1/v${{ steps.release.outputs['app1--version'] }}"
          git push origin "app1/v${{ steps.release.outputs['app1--version'] }}"

      - name: Tag app2 release
        if: ${{ steps.release.outputs['app2--release_created'] }}
        run: |
          git tag "app2/v${{ steps.release.outputs['app2--version'] }}"
          git push origin "app2/v${{ steps.release.outputs['app2--version'] }}"